### ISSUE TITLE
Checkins not showing up

### ISSUE THREAD

**Issue by cleverdevil** [cleverdevil/together#19]
The checkins from my personal website:

    https://cleverdevil.io/content/locations/

... do not show up on our "Checkins" map.

**Comment by cleverdevil** [comment]
FWIW, I am using Monocle as the Microsub server and the source is `https://cleverdevil.io/content/all/` as `microformats` source.

**Comment by grantcodes** [comment]
Looks like an issue for @aaronpk or your own site. Monocle isn't picking up your checkin location:

```JSON
{
  "type": "entry",
  "published": "2018-01-14T21:30:11+00:00",
  "url": "https://cleverdevil.io/2018/checked-into-california-pizza-kitchen",
  "syndication": [
    "https://www.swarmapp.com/user/62573/checkin/5a5bcbd3f62e097341a2febc"
  ],
  "name": "Checked into California Pizza Kitchen",
  "content": {
    "text": "Lunch with friends.",
    "html": "<p>Lunch with friends.</p>"
  },
  "author": {
    "type": "card",
    "name": "Jonathan LaCour",
    "url": "https://cleverdevil.io/profile/cleverdevil",
    "photo":
      "https://cleverdevil.io/file/2fa19f964fb8970faaf20b909c69d6cb/thumb.png"
  }
}
```

**Comment by aaronpk** [comment]
Looking at your site, I see a `geo` property on the `h-entry` which is not something I've heard of before. That should be `location` instead. I'm not sure when/why Known is doing this.

**Comment by cleverdevil** [comment]
Thanks for the feedback, @aaronpk. I’ll open a bug with Known and send a PR over to fix it when I get a chance. Might not be until the weekend 😉

**Comment by aaronpk** [comment]
Some pointers on location for posts:

* h-entry has a property `location` which can contain `h-geo` among other values. That should be used for the location of any post, not just checkins. http://microformats.org/wiki/h-entry#Core_Properties
* The checkin vocabulary is still experimental, and is documented at https://indieweb.org/checkin#Publish with example markup

**Comment by cleverdevil** [comment]
Resolved with a fix in Known.
