### ISSUE TITLE
Photos from source not loading

### ISSUE THREAD

**Issue by cleverdevil** [cleverdevil/together#20]
If you add `http://feeds.kottke.org/json` as a source, images in the feed items won't load. He is using relative image paths in his image markup.

**Comment by grantcodes** [comment]
I think this should probably be normalized on the server side?

**Comment by aaronpk** [comment]
oh sneaky, the img src URLs in the html are relative... what does JSONFeed say about that? I need to know what base URL to resolve against. I'm assuming I would resolve against the item URL rather than the URL of the jsonfeed.

**Comment by grantcodes** [comment]
Pretty sure this should be handled on the server, so closing for now
