### ISSUE TITLE
Collapsible cards

### ISSUE THREAD

**Issue by cleverdevil** [cleverdevil/together#22]
Having cards be able to be "collapsed" would be nice. This way, on channels with a lot of items, you could more easily skim through title/headline and then choose to expand a "Read More" of a particular article if desired.

**Comment by grantcodes** [comment]
I was planning to do a 2 things:

1. A compressed view that would only show a one line preview of a post (like a more classic feed reader)
2. Collapsing article posts like you suggested so you don't need to scroll so much.

**Comment by cleverdevil** [comment]
I tried working on this using the material-ui `collapsable` properties, and couldn't get it working. Might need some additional investigation.

**Comment by grantcodes** [comment]
Added content collapsing in v 1.11.0
