### ISSUE TITLE
Cannot log in: 

### ISSUE THREAD

**Issue by cleverdevil** [cleverdevil/together#23]
When attempting to login to Together with the latest update, I get an error in the JavaScript console:

https://cleverdevil.io/s/LPd2otbKQH.png

`POST http://localhost:3000/api/micropub/getAuthUrl 404 (Not Found) micropub-api.js:39`

Looks like perhaps some code didn't get fully checked in. I've tried in both Safari and Chrome on macOS.

**Comment by grantcodes** [comment]
Should work fine locally on the latest build
