### ISSUE TITLE
Filter by read status

### ISSUE THREAD

**Issue by cleverdevil** [cleverdevil/together#29]
It’d be great to have a way to view only the unread items in a channel.

**Comment by grantcodes** [comment]
Don't think this will be possible without changes to the spec. As there isn't really any way to know where unread items are in pages of data. If it is on page 100 the app would need to load and look through all those pages just to find it

**Comment by EdwardHinkle** [comment]
Wait, the spec is being worked out on this! It's in Aperture and Drupal
https://github.com/indieweb/microsub/issues/24

**Comment by grantcodes** [comment]
Cool thanks Eddie, good to know! I may open an issue on the new repo for this.

**Comment by EdwardHinkle** [comment]
Ohh, you changed repos :) Cool.
