### ISSUE TITLE
Responsive layout adjustments

### ISSUE THREAD

**Issue by cleverdevil** [cleverdevil/together#30]
At least on my iPhone X, together is just barely too wide to fit the screen properly. It’s close!

**Comment by grantcodes** [comment]
yeah same here. need to do something about it

**Comment by grantcodes** [comment]
Let me know if it works for you now with the updated layout (you can't miss it 😃)

**Comment by cleverdevil** [comment]
Works great now on iOS!

On the desktop now, its a bit too aggressive at collapsing the channels list. When I have the screen real estate, I prefer having it open.

Otherwise, looks great :)

**Comment by cleverdevil** [comment]
This is fixed on Desktop now, with the latest changes. Closing!
