### ISSUE TITLE
Channel List doesn't scroll

### ISSUE THREAD

**Issue by EdwardHinkle** [cleverdevil/together#35]
I have 19 channels in Microsub, so just over half appear in the list before being cut off. It seems to fit 11 of my channels (some of them take up two lines because they are too long). It seems the the max single line channels is probably around 13 or 14. Adding an overflow-y scroll would help allow scrolling that view.

**Comment by grantcodes** [comment]
Think I actually just fixed this before you opened this issue.

Are you using the new build? It's a blue slate color.

**Comment by EdwardHinkle** [comment]
Hmm, I was using the hosted version, I haven’t downloaded the new version since you fixed my login issue. So it depends if the hosted version was updated at the time I posted the issue. I download the latest code locally and check it out and report back if I continue to have the issue.

(Originally published at: https://eddiehinkle.com/2018/02/14/10/reply/)

**Comment by grantcodes** [comment]
The hosted version is fully up to date now. You might need to wait and refresh for the PWA to update.

**Comment by EdwardHinkle** [comment]
Yep fixed

**Comment by EdwardHinkle** [comment]
So it works fine on my iOS device in Safari but in Safari on macOS on my laptop, it won't scroll...

**Comment by EdwardHinkle** [comment]
I tried to tweak it in the browser DOM but I'm not 100% sure what it is, but I feel like it has something to do with the flex layout that might be throwing it off. That said, I don't know enough about flex to be able to debug it. I tried adding overflow-y on a couple elements and it didn't change anything.
