### ISSUE TITLE
Add smooth scrolling to mobile devices/iOS 

### ISSUE THREAD

**Issue by EdwardHinkle** [cleverdevil/together#36]
When reading an article in “classic view” on a mobile device (you select the summary segment which loads the full page article) scrolling is not smooth on iOS. Using some css attributes this can be fixed: https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

**Comment by grantcodes** [comment]
Ok I added that css, only to the classic view as I am pretty sure it causes scroll bars to appear on other platforms which I don't really want. But let me know if it works better for you now

**Comment by EdwardHinkle** [comment]
Works much better. Since in classic view the articles can be long it’s helpful!
