### ISSUE TITLE
empty channel view after adding feed

### ISSUE THREAD

**Issue by sknebel** [cleverdevil/together#40]
After adding a feed, no channel items are visible ("🤷‍ Nothing to show - Maybe you need to subscribe to a site or select a different channel"). I have to switch channels to another one to see items again, clicking the same channel again does not work.

**Comment by grantcodes** [comment]
I've made the channel reload 1 second after the new feed is added.

But chances are the micropub server won't have updated that quickly, don't really thing I can do much more unless servers start sending real time updates of some sort
