### ISSUE TITLE
logout doesn't seem to do anything until page reload

### ISSUE THREAD

**Issue by sknebel** [cleverdevil/together#41]
After pressing "logout" in the settings, not only was I not returned to a login screen (as I would have expected), together also was still useable and I could make changes that were sent to the microsub server.

The IndieAuth spec now has a way to do [token revocation](https://indieauth.spec.indieweb.org/#x6-3-5-token-revocation) too.

**Comment by grantcodes** [comment]
It should now log you out properly with the new backend.

But doesn't do token revocation yet
