### ISSUE TITLE
mark posts read button is sometimes missing

### ISSUE THREAD

**Issue by aaronpk** [cleverdevil/together#43]
I can't quite figure out the circumstances under which this happens, but sometimes the "mark posts read" button is missing even though there are a bunch of unread posts in the channel.

**Comment by grantcodes** [comment]
I think this happens when you hit mark as read then change channel before the server responds with a success message. I need to pass the channel uid along with the responses instead of always changing the state of the current channel

**Comment by grantcodes** [comment]
Think it should be fixed in v1.0.4, but may be for some other reason. If so feel free to reopen
