### ISSUE TITLE
load webfonts from secure origins

### ISSUE THREAD

**Issue by sknebel** [cleverdevil/together#44]
Currently getting mixed-media warnings for http://fonts.gstatic.com/s/opensans/v15/mem8YaGs126MiZpBA-UFVZ0b.woff2 and http://www.inoreader.com/css/fonts/Inoreader-UI-Icons-Font.ttf?t6rt67 . The latter probably also is not intended for public use by random projects?

**Comment by grantcodes** [comment]
Not checked, but I think that might be added by html content in a post in one of your channels? I definitely didn't add those fonts on purpose

**Comment by sknebel** [comment]
No, this happens even if the microsub server isn't functional enough to actually serve posts yet ;)

I only get the warnings in Firefox though, it might be stricter than other browsers here?

**Comment by sknebel** [comment]
... and now I can not reproduce it. *maybe* the Inoreader browser extension I have running did something wonky? I'll close this for now and report back if it happens again, I can't see where together should be triggering this either and will thus assume something else caused it.

**Comment by sknebel** [comment]
Just to confirm: Firefox seems to show loading errors from totally different tabs in devtools occasionally! left the console open and now have 10 different errors accumulated there, which clearly have nothing to do with together.
