### ISSUE TITLE
channels with slashes in the uid do not work

### ISSUE THREAD

**Issue by sknebel** [cleverdevil/together#45]
@aaronpk's monocle had the same issue, there it happened because the channel ID gets used as the path component, which is also the case with together and might cause problems here too.

I have a publicly running demo server that accepts any auth token and has a channel like that at http://svenknebel.de:8089/microsub, you can use this for testing if you want. https://alltogethernow.io/channel/slashes/slashes does not work, the other channels do.

**Comment by grantcodes** [comment]
Ok think this should be fixed now. Not actually tested though... So let me know if you can

**Comment by sknebel** [comment]
Sorry for only now getting back to you. This seems to have fixed the front-end side of things, and my backend receives a correctly formed request for the channel contents now, but in the browser I still only get the "🤷‍ Nothing to show" screen.

**Comment by grantcodes** [comment]
Hopefully that was unrelated and should be fine in v3
