### ISSUE TITLE
White page when using map layouts

### ISSUE THREAD

**Issue by pstuifzand** [cleverdevil/together#49]
I get a white page when using the map layout. I get the following error in the console: "Cannot read property 'marker' of null"  at checkins.js:122

I'm not sure, it looks like the problem could that I have "checkin" property that is and empty object.

(Originally published at: https://publog.stuifzandapp.com/posts/525)

**Comment by grantcodes** [comment]
Your issue might be fixed in 1.1.5

But the location filtering stuff is going to need some more work, it may still break depending on differences between the `location` and `checkin` properties and also if you ever happen to be exactly on 0 longitude or latitude
