### ISSUE TITLE
Prettier theme / colors

### ISSUE THREAD

**Issue by grantcodes** [cleverdevil/together#60]
Not really feeling the slate blue color any more.

Would like to have a more unique theme / branding

**Comment by grantcodes** [comment]
I started working on an update to the theme. I am planning on making the dark theme darker and the light theme lighter with some nicer colors. I think I may need to tweak the blue color on the light theme as it is a bit strong, but apart from that I prefer it.

It also removes the font and uses the provided system font as well. (Screenshots on windows)

![image](https://user-images.githubusercontent.com/3390268/42401799-54f3b286-8145-11e8-97d7-4488f34657db.png)

![image](https://user-images.githubusercontent.com/3390268/42401770-2b4d3448-8145-11e8-8589-0fe9e8f6a775.png)

**Comment by cleverdevil** [comment]
This looks awesome! I also think that the blue in the lighter version would benefit from some toning down, but other than that it looks fantastic. I can't wait to try it on iOS and macOS!

[](https://brid.gy/publish/github)

(Originally published at: https://cleverdevil.io/2018/this-looks-awesome-i-also-think-that-the-blue-in)

**Comment by grantcodes** [comment]
![image](https://user-images.githubusercontent.com/3390268/42405047-276b7524-815e-11e8-9526-832df86e2d1b.png)

 How about a something closer to this for the light theme
