### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by jernst** [cleverdevil/together#61]
If there is one, I cannot find it :-)

**Comment by grantcodes** [comment]
I honestly don't know much about licenses. Do you have a recommendation? I think anyone should be free to use the code however they want.

**Comment by cleverdevil** [comment]
Let's go with the MIT license. Extremely permissive.

**Comment by EdwardHinkle** [comment]
That's great. Indigenous is MIT as well

**Comment by cleverdevil** [comment]
Done in https://github.com/cleverdevil/together/commit/32fa076986b576cbd520c0bd4f71a5b9ef08894a
