### ISSUE TITLE
On the return leg of authentication, the login dialog comes up again

### ISSUE THREAD

**Issue by jernst** [cleverdevil/together#66]
1. I visit alltogethernow.io and enter my site URL.
2. I get redirected to the authentication provider etc etc.
3. Once I approve the authorization, I get redirected to alltogethernow.io
4. The first thing that comes up is the "Login" popup again, which is very confusing.
5. Only after some time does the popup go away on its own, and I am indeed logged in.

It would be good to remove step 4.

**Comment by grantcodes** [comment]
Will be different in v3
