### ISSUE TITLE
De-markup Ryan

### ISSUE THREAD

**Issue by jernst** [cleverdevil/together#68]
I don't know whether this is an Aperture thing or a Together thing, but @snarfed's posts show up like this:

<img width="417" alt="screen shot 2018-06-28 at 13 33 58" src="https://user-images.githubusercontent.com/874785/42059392-1ddeb570-7ad8-11e8-9563-b0f19027aab5.png">

**Comment by grantcodes** [comment]
If this was an error with together it should be fixed by now, but more likely an error with the server
