### ISSUE TITLE
Add native support for Indiepaper

### ISSUE THREAD

**Issue by cleverdevil** [cleverdevil/together#70]
[Regarding Together](https://github.com/cleverdevil/together)

Now that I've launched [Indiepaper](https://indiepaper.cleverdevil.io), I'd love to see Together add native support for sending articles to Indiepaper with the click of a button. This would require a few configuration settings, including the configuration of a bearer token and a target micropub destination.

(Originally published at: https://cleverdevil.io/2018/add-native-support-for-indiepaper)

**Comment by cleverdevil** [comment]
After we do this manually, it we would be good to brainstorm how we could potentially make the configuration discoverable from the user's website or microsub server, or both.

(Originally published at: https://cleverdevil.io/2018/after-we-do-this-manually-it-we-would-be-good)

**Comment by EdwardHinkle** [comment]
@aaronpk and I were discussing this and he brought up this issue on Aperture: https://github.com/aaronpk/Aperture/issues/36

**Comment by grantcodes** [comment]
Yeah it would be cool to have built in, but I don't know how you would make it fully work across all servers, how would you know it supports micropub posting?

**Comment by cleverdevil** [comment]
The simplest option would just be to let people manually configure Indiepaper by having them enter their Bearer token and Micropub Endpoint from Aperture.

I think @aaronpk is considering making it possible to IndieAuth directly with a Microsub channel in Aperture, which would provide a better experience eventually. In the meantime a manual configuration option would still be useful.

[](https://brid.gy/publish/github)

(Originally published at: https://cleverdevil.io/2018/the-simplest-option-would-just-be-to-let-people-manually)

**Comment by cleverdevil** [comment]
With the native macOS integration for Indiepaper and native iOS integration on the way, I don't think we should do this.
