### ISSUE TITLE
micropub: specify html key in content property

### ISSUE THREAD

**Issue by herestomwiththeweather** [cleverdevil/together#74]
it seems section 4.1.3 "New Article with HTML" from https://www.w3.org/TR/micropub/#h-new-article-with-html should be accommodated so that html is properly rendered on a micropub server.  for example, using micropub-helper, the following renders correctly:

```
  micropub.create({
    type: ['h-entry'],
    properties: {
      content: [
        {
	  "html": 'This is a <strong>test post</strong>'
        }
      ],
    },
  })
```

whereas the following without the html key does not:

```
  micropub.create({
    type: ['h-entry'],
    properties: {
      content: ['This is a <strong>test post</strong>' ],
    },
  })
```

**Comment by grantcodes** [comment]
This was actually an issue with the [micropub-client-editor](https://github.com/grantcodes/micropub-client-editor) which I updated. Hopefully should be fine now

**Comment by herestomwiththeweather** [comment]
cool! thanks.
