### ISSUE TITLE
Error when marking unread

### ISSUE THREAD

**Issue by jackjamieson2** [cleverdevil/together#75]
I'm adding `mark_read` and `mark_unread` support to my microsub server. 

`mark_read` seems to work fine

When I click `mark_unread` from together my server correctly updates the status of the post, but Together displays 'Error marking as unread' and displays the post as though it were still read.  When I reload the channel timeline, it is correctly recognized as unread. 

Should my server return anything to Together to avoid this error? As far as I understand `mark_read` does not require a return value, so I expect `mark_unread` should be the same.

**Comment by jackjamieson2** [comment]
Turns out this was a mistake on my end. I returned a null value by mistake, which seemed to trigger the error. Edited my code to return nothing and the error is gone :)

**Comment by jackjamieson2** [comment]
Noticed that the error message goes away when I return the timeline, but I would expect mark_unread to work without a return value, same as mark_read.

Since mark_unread is not in the Microsub spec, maybe we can propose an addition?

**Comment by grantcodes** [comment]
Hmm yeah, together expects any timeline action to return valid json, even if it is just empty.

I'm not sure if the spec should say a json response is always required or if 200 status is ok?

Probably need @aaronpk to chime in

**Comment by jackjamieson2** [comment]
Thanks Grant, that sounds reasonable, but I agree it'd be nice to clarify in the spec.
