### ISSUE TITLE
Success message says "liked" instead of "reposted"

### ISSUE THREAD

**Issue by jackjamieson2** [cleverdevil/together#76]
When I click repost, the success message says "Successfully liked {permalink}" instead of "Successfully reposted {permalink}".

The actual post on my site is a repost, so this looks like it's just the success message.

Perhaps I could add a feature request here too - would it be possible to display a link to the post created on my site?  And/or make the success notice remain on screen below the post? 

A permanent success notice would help prevent double posts (expanding on #69) and displaying the link to the post on my site would make it easier to verify and potentially edit replies after they are posted

**Comment by grantcodes** [comment]
Ok so I updated the notification to that it says repost not like.

I'm not sure about the best way to show the link to the post on your site though. I still want to the show the url that you reposted. Maybe just a button that says "view" would work?

And permanent notices would require a bit of a rework of the notification system, it's pretty basic at the moment.
