### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by EdwardHinkle** [cleverdevil/together#8]
I have both node.js and yarn installed on my machine.

I run yarn start and I get the following output:

```
yarn run v1.1.0
$ react-scripts start
/bin/sh: react-scripts: command not found
error Command failed with exit code 127.
```

**Comment by grantcodes** [comment]
You probably just need to run `yarn install` first.

I'll add that step to the readme

**Comment by EdwardHinkle** [comment]
Confirmed, that fixed it :)
