### ISSUE TITLE
Polling channels in the background

### ISSUE THREAD

**Issue by sebsel** [cleverdevil/together#82]
While implementing a Microsub backend myself, I noticed how Together keeps polling for new channels. It does this when the main window is open, for about ever 10/15 seconds, but I noticed it also occurs when the main window is closed, every 30-or-so seconds. What is the point of that? I find it a bit excessive.

**Comment by sebsel** [comment]
Okay, I was expecting a bug in my FireFox, which could've been running another window somewhere. And indeed: killing FireFox got rid of the 30 second poll. The 15 second poll is then just two windows opened, both updating.

I think the 30-second poll is there to update the read-counts? It might be just a valid use-case. I was freaking out because of the zombie-window :)

**Comment by grantcodes** [comment]
Yes, it polls to update the channel list / read count and the current channel you are on to update content.

It should poll once per minute, but may be doing the two different requests every minute. It's the best option until microsub supports some sort of push mechanism.
