### ISSUE TITLE
Time out when logging in

### ISSUE THREAD

**Issue by jackjamieson2** [cleverdevil/together#87]
Sometimes logging in fails due to timeout.

1. I enter my url to log in 
2. I am redirected to the permissions screen provided by WordPress-IndieAuth. I click allow.
3. I am returned to alltogether.io, where I see the login box for a moment, and then a timeout error appears briefly.
4. I run through this process again, and the login succeeds.

Typically my first login attempt in a sessions fails, so I have to attempt to log in twice.  Not sure if this is just an aggressive timeout schedule or something on my end

My website specs:
https://jackjamieson.net running WordPress

Plugin versions:
- IndieAuth 3.1.11
- Micropub 2.0.5
- Yarns Microsub Server(latest dev branch)

**Comment by grantcodes** [comment]
I'm going to hope this will be improved in v3, if not feel free to reopen on the new repo :)
