### ISSUE TITLE
Feed list doesn't scroll

### ISSUE THREAD

**Issue by jackjamieson2** [cleverdevil/together#89]
When trying to follow a site that has many feeds, the list of feeds is cut off on my screen (e.g. see the screenshot below when trying to follow david.shanske.com).

<img width="428" alt="screen shot 2019-01-04 at 4 31 13 pm" src="https://user-images.githubusercontent.com/12275399/50712084-31247380-103e-11e9-9b3e-0bcae6dd7354.png">

This means I can't see all the feeds, and the cancel button is hidden. 

Two ideas:
- The list should scroll
- Even if the list were changed to scroll, it might be nice to ensure the cancel button is visible at all times to avoid potential confusion

**Comment by grantcodes** [comment]
Will be fixed in v3
