### ISSUE TITLE
Endpoints parsing error when signing in with Micro.blog blog URL

### ISSUE THREAD

**Issue by pamoroso** [cleverdevil/together#94]
When I try to sign into https://alltogethernow.io/ by entering the URL of my Micro.blog-hosted blog https://amoroso.micro.blog into the login dialog and approving Together's access request in Micro.blog, I get the error `Could not log in: could not parse all required endpoints from your site` from Together. To reproduce:

1. visit https://alltogethernow.io/
2. under Your Website URL, enter https://amoroso.micro.blog/
3. in Micro.blog, click **Approve**

**Comment by cleverdevil** [comment]
@pamoroso I don't see a "microsub" `<link rel>` in your website. Using Together requires a Microsub account.

**Comment by cleverdevil** [comment]
Sounds like it may be an issue of the microsub endpoint for Micro.blog not being included in the theme you're using. @manton is aware too, and will check it out on his end.

I do think @grantcodes and I should make Together give a much better error message in this case. It should say, specifically, which endpoints it expects to find, and which it wasn't able to discover.

**Comment by manton** [comment]
I've commented in the Micro.blog Slack, but to follow up here: I think the custom theme for this blog is using an out of date template that doesn't include Microsub support. It can be fixed by using the built-in theme on Micro.blog or adding the following line to the `head.html` template:

```<link rel="microsub" href="https://micro.blog/microsub" />```

**Comment by cleverdevil** [comment]
Thanks, @manton! I’m going to go ahead and close this ticket.
